name: 'Build Docker Images'
description: 'Build frontend and backend Docker images with caching'
author: 'Synergia Team'

inputs:
  version:
    description: 'Version tag for the images'
    required: true
  frontend-path:
    description: 'Path to frontend Dockerfile'
    required: false
    default: './client'
  backend-path:
    description: 'Path to backend Dockerfile'
    required: false
    default: './server'

outputs:
  frontend-image:
    description: 'Frontend image name with tag'
    value: synergia-frontend:${{ inputs.version }}
  backend-image:
    description: 'Backend image name with tag'
    value: synergia-backend:${{ inputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=moby/buildkit:latest
    
    - name: Build frontend image
      shell: bash
      run: |
        echo "🔨 Building frontend image..."
        docker buildx build \
          --load \
          --cache-from=type=gha,scope=frontend \
          --cache-to=type=gha,mode=max,scope=frontend \
          --tag synergia-frontend:${{ inputs.version }} \
          --tag synergia-frontend:latest \
          ${{ inputs.frontend-path }}
        echo "✅ Frontend image built successfully"
    
    - name: Build backend image
      shell: bash
      run: |
        echo "🔨 Building backend image..."
        docker buildx build \
          --load \
          --cache-from=type=gha,scope=backend \
          --cache-to=type=gha,mode=max,scope=backend \
          --tag synergia-backend:${{ inputs.version }} \
          --tag synergia-backend:latest \
          ${{ inputs.backend-path }}
        echo "✅ Backend image built successfully"
    
    - name: List built images
      shell: bash
      run: |
        echo "📦 Built images:"
        docker images | grep synergia
