# ECM Monitoring - Configuration Docker
# 
# Pour le développement : docker compose -f docker-compose.dev.yml up
# Pour la production    : docker compose -f docker-compose.prod.yml up
#
# Ce fichier est maintenu pour compatibilité mais il est recommandé 
# d'utiliser les fichiers spécifiques dev/prod

include:
  - docker-compose.dev.yml
