name: Build and Test

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Docker Compose est préinstallé sur GitHub Actions runners
      # Si nous rencontrons des problèmes avec la commande 'docker compose' (sans tiret),
      # utilisons la commande docker-compose avec tiret
      - name: Check Docker Compose Installation
        run: docker compose version || docker-compose version
      
      - name: Build images for testing
        run: docker-compose build --build-arg NODE_ENV=test
      
      - name: Start services
        run: docker-compose up -d
      
      - name: Wait for services to start
        run: sleep 30
      
      # Test the backend
      - name: Run backend tests
        run: docker-compose exec -T backend npm test
        
      # Optionally run frontend tests if configured
      # - name: Run frontend tests
      #   run: docker-compose exec -T frontend npm test
      
      - name: Stop services
        run: docker-compose down
