name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push images
      run: |
        docker build -t ghcr.io/${{ github.repository }}-frontend:latest ./client
        docker build -t ghcr.io/${{ github.repository }}-backend:latest ./server
        docker push ghcr.io/${{ github.repository }}-frontend:latest
        docker push ghcr.io/${{ github.repository }}-backend:latest
