name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push multi-architecture images
      run: |
        # Build frontend avec support multi-architecture
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --tag ghcr.io/${{ github.repository }}-frontend:latest \
          --tag ghcr.io/${{ github.repository }}-frontend:${{ github.sha }} \
          --push \
          ./client
          
        # Build backend avec support multi-architecture  
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --tag ghcr.io/${{ github.repository }}-backend:latest \
          --tag ghcr.io/${{ github.repository }}-backend:${{ github.sha }} \
          --push \
          ./server
