name: Test Dev Branch

on:
  push:
    branches: [ dev ]

jobs:
  test-dev:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Docker Compose est préinstallé sur GitHub Actions runners
      # Si nous rencontrons des problèmes avec la commande 'docker compose' (sans tiret),
      # utilisons la commande docker-compose avec tiret
      - name: Check Docker Compose Installation
        run: docker compose version || docker-compose version
      
      - name: Build images for testing
        run: docker-compose build --build-arg NODE_ENV=test
      
      - name: Start services
        run: docker-compose up -d
      
      - name: Wait for services to start
        run: sleep 30
      
      - name: Run backend tests
        run: docker-compose exec -T backend npm test
      
      - name: Application Info
        run: |
          echo "✅ Tests passed successfully!"
          echo "Pour tester l'application manuellement:"
          echo "1. Clonez le dépôt"
          echo "2. Exécutez docker-compose up -d"
          echo "3. Accédez à http://localhost pour le frontend"
          echo "4. L'API est disponible sur http://localhost:5001"
      
      - name: Stop services
        run: docker-compose down
