name: Test Dev Branch

on:
  push:
    branches: [ dev ]

jobs:
  test-dev:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Install Docker Compose
        run: |
          # Vérifier si Docker Compose est déjà installé
          if ! docker compose version &> /dev/null; then
            # Installer Docker Compose v2 directement
            DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
            mkdir -p $DOCKER_CONFIG/cli-plugins
            curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
            chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
          fi
          # Vérifier l'installation
          docker compose version
      
      - name: Build images
        run: docker compose build
      
      - name: Start services
        run: docker compose up -d
      
      - name: Wait for services to start
        run: sleep 30
      
      - name: Run backend tests
        run: docker compose exec -T backend npm test
      
      - name: Application Info
        run: |
          echo "✅ Tests passed successfully!"
          echo "Pour tester l'application manuellement:"
          echo "1. Clonez le dépôt"
          echo "2. Exécutez docker compose up -d"
          echo "3. Accédez à http://localhost pour le frontend"
          echo "4. L'API est disponible sur http://localhost:5001"
      
      - name: Stop services
        run: docker compose down
